# Generated by Django 3.2.8 on 2021-11-26 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BPBOnlineBookShopMongoDBApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BPBCatalogCollection',
        ),
    ]
